FROM python:3.11-slim-bullseye
WORKDIR /code

ENV PYTHONPATH="/code"
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /code/secrets
RUN mkdir -p /code/logs/
COPY api/ /code/api/
COPY docker/requirements/statsapi-requirements.txt /code/requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt -q

EXPOSE 8080

ENTRYPOINT ["fastapi", "run", "/code/api/main.py", "--port", "8080"]