services:
  pricecatcher-scraper:
    build:
      context: "${PWD}"
      dockerfile: "${PWD}/docker/Dockerfile.pricecatcher"
    secrets:
      - source: "SERVICE_ACCOUNT_FILE"
        target: "/code/secrets/SERVICE_ACCOUNT_FILE.json"
      - source: "ENVIRONMENT"
        target: "/code/secrets/.env"
    image: $DOCKER_TAG
    ports:
      - 8080

secrets:
  SERVICE_ACCOUNT_FILE:
    file: "${PWD}/secrets/SERVICE_ACCOUNT_FILE.json"
  ENVIRONMENT:
    file: "${PWD}/secrets/.env"